<?php

/**
 * ========================================================
 * ==================== CONFIG ============================
 * ========================================================
 */

$an_plugin_config = [
	'plugin_name' => 'Auction Nudge',
	'plugin_version' => '8.2.1',
	'custom_field_prefix' => 'an',
	'shortcode' => 'auction-nudge',
	'username_bad' => ['.', "\$", '!', '*'],
	'username_good' => ['__dot__', '__dollar__', '__bang__', '__star__'],
	'keyword_chars_decoded' => [
		'%20',
		' ',
		'"',
		',',
		'(',
		')',
	],
	'keyword_chars_encoded' => [
		'+',
		'+',
		'__quote__',
		'__comma__',
		'__lbra__',
		'__rbra__',
	],
	//Requests
	'item_request' => [
		'endpoint' => '//www.auctionnudge.com/feed/item/js',
		'content_type' => 'text/javascript',
		'cache_minutes' => 15,
	],
	//Item tool parameters
	'item_parameter_groups' => [
		'feed' => [
			'name' => 'Feed options',
			'description' => '',
		],
		'display' => [
			'name' => 'Display options',
			'description' => '',
		],
		'advanced' => [
			'name' => 'Advanced options',
			'description' => '',
		],
	],
	'item_parameters' => [
		//Step one
		'item_SellerID' => [
			'name' => 'item_SellerID',
			'id' => 'item_SellerID',
			'tip' => 'This is your eBay ID &ndash; the username you are known by on eBay and appears on your listings. This is not your store name.',
			'group' => 'feed',
			'title' => 'eBay Username',
			'output_processing' => [
				'username_encode',
			],
		],
		'item_siteid' => [
			'name' => 'item_siteid',
			'id' => 'item_siteid',
			'tip' => 'This is where your items are usually listed. The site you choose will determine where you link to and what currency is displayed.',
			'type' => 'select',
			'options' => [
				'0' => 'eBay US',
				'3' => 'eBay UK',
				'2' => 'eBay Canada',
				'15' => 'eBay Australia',
				'23' => 'eBay Belgium',
				'77' => 'eBay Germany',
				'71' => 'eBay France',
				'186' => 'eBay Spain',
				'16' => 'eBay Austria',
				'101' => 'eBay Italy',
				'146' => 'eBay Netherlands',
				'205' => 'eBay Ireland',
				'193' => 'eBay Switzerland',
			],
			'default' => '0',
			'group' => 'feed',
			'title' => 'eBay Site',
		],
		//Step two

		'item_add_details' => [
			'name' => 'item_add_details',
			'id' => 'item_add_details',
			'tip' => 'When View Details is enabled, instead of linking directly to the item on eBay, additional item details will be displayed. Details include extra images, item description, item specifics, your user profile and a \'View on Bay\' button. The Advertising Disclosure is displayed above the details.',
			'type' => 'radio',
			'group' => 'display',
			'title' => 'View Details',
			'default' => '0',
			'options' => [
				'1' => 'Yes',
				'0' => 'No',
			],
		],
		'item_user_profile' => [
			'name' => 'item_user_profile',
			'id' => 'item_user_profile',
			'tip' => 'If enabled, your eBay Username, positive feedback percentage, feedback score and feedback star (if applicable) will be displayed above your listings.',

			'type' => 'radio',
			'group' => 'display',
			'title' => 'User Profile',
			'default' => '0',
			'options' => [
				'1' => 'Yes',
				'0' => 'No',
			],
		],
		'item_page' => [
			'name' => 'item_page',
			'id' => 'item_page',
			'tip' => 'If you enable this option and have more items listed than the value for the \'Items per Page\' option above, users can paginate between multiple pages of items.',
			'type' => 'radio',
			'group' => 'display',
			'title' => 'Pagination',
			'default' => 'init',
			'options' => [
				'init' => 'Yes',
				'' => 'No',
			],
		],
		'search_box' => [
			'name' => 'search_box',
			'id' => 'search_box',
			'tip' => 'If enabled, a search box will appear above the items which will allow users to search all of your active eBay items. Note: Only item titles are searched, not descriptions.',
			'tip_link' => 'https://www.auctionnudge.com/help/options#search-box',
			'type' => 'radio',
			'group' => 'display',
			'title' => 'Search Box',
			'default' => '1',
			'options' => [
				'1' => 'Yes',
				'0' => 'No',
			],
		],

		'item_cats_output' => [
			'name' => 'cats_output',
			'id' => 'cats_output',
			'tip' => 'Once enabled, a list of categories for your items (if you have items for sale in more than one category) will be displayed above your items. This allows users to filter your items by category. The categories shown are eBay categories and not custom/store categories which can not be displayed. Use the Category ID option (Advanced Options) to specify a starting category.',
			'tip_link' => 'https://www.auctionnudge.com/help/options#category-list',
			'type' => 'select',
			'options' => [
				'dropdown' => 'Dropdown',
				'unstyled' => 'Unstyled (advanced)',
				'' => 'None',
			],
			'default' => 'dropdown',
			'group' => 'display',
			'title' => 'Category List',
		],

		'item_theme' => [
			'name' => 'item_theme',
			'id' => 'item_theme',
			'tip' => 'Your items will display differently on your site depending on which theme you choose. You can change how these themes displaying your listings using CSS rules.',
			'tip_link' => 'https://www.auctionnudge.com/customize/appearance',
			'type' => 'select',
			'options' => [
				'responsive' => 'Responsive',
				'grid' => 'Grid View',
				'columns' => 'Column View',
				'carousel' => 'Carousel',
				'simple_list' => 'Simple List',
				'details' => 'Image and Details',
				'images_only' => 'Images Only',
				'unstyled' => 'Unstyled (advanced)',
			],
			'default' => 'responsive',
			'group' => 'display',
			'title' => 'Theme',
		],
		'item_carousel_scroll' => [
			'name' => 'item_carousel_scroll',
			'id' => 'item_carousel_scroll',
			'tip' => 'This option specifies how may items will be visible in the carousel at one time. Use in conjunction with \'Item width\' to set the overall carousel width, i.e. 140px * 4 = 560px.',
			'group' => 'display',
			'title' => 'Number of Items to Scroll',
			'default' => '2',
		],
		'item_carousel_width' => [
			'name' => 'item_carousel_width',
			'id' => 'item_carousel_width',
			'tip' => 'Specify in pixels how wide each item in the carousel will be. Use in conjunction with \'Number of items to scroll\' to set the overall carousel width, i.e. 140 * 4 = 560px.',
			'group' => 'display',
			'title' => 'Item Width',
			'default' => '240',
		],
		'item_carousel_auto' => [
			'name' => 'item_carousel_auto',
			'id' => 'item_carousel_auto',
			'tip' => 'This option specifies how often, in seconds the carousel should auto scroll. If set to 0 auto scroll is disabled.',
			'group' => 'display',
			'title' => 'Auto Scroll',
			'default' => '0',
		],
		'item_grid_cols' => [
			'name' => 'item_grid_cols',
			'id' => 'item_grid_cols',
			'tip' => 'Use this option to specify how many columns to display in grid view.',
			'group' => 'display',
			'title' => 'Grid Columns',
			'default' => '2',
		],
		'item_grid_width' => [
			'name' => 'item_grid_width',
			'id' => 'item_grid_width',
			'tip' => 'Use this option to specify how wide the grid should be. This can be specified in either pixels (px) or as a percentage (%)',
			'group' => 'display',
			'title' => 'Grid Width',
			'default' => '100%',
			'output_processing' => [
				'replace_percent',
			],
		],
		'item_MaxEntries' => [
			'name' => 'item_MaxEntries',
			'id' => 'item_MaxEntries',
			'tip' => 'This is the number of items you want display per page, the maximum value is 100. You can display multiple pages of items using the \'Pagination\' option.',
			'group' => 'display',
			'title' => 'Items per Page',
			'default' => '6',
		],
		'item_img_size' => [
			'name' => 'item_img_size',
			'id' => 'item_img_size',
			'tip' => 'Specify in pixels the maximum image size. Depending on the image ratio, the image width or height will not exceed this size. At larger sizes, higher quality images (and therefore a larger file size) are used.',
			'tip_link' => 'https://www.auctionnudge.com/customize/appearance#image-size',
			'group' => 'display',
			'title' => 'Image Size',
			'default' => '140',
		],
		'item_show_logo' => [
			'name' => 'item_show_logo',
			'id' => 'item_show_logo',
			'tip' => 'This option specifies if you want to display the eBay logo alongside your listings.',
			'type' => 'radio',
			'group' => 'display',
			'title' => 'Show eBay Logo?',
			'default' => '1',
			'options' => [
				'1' => 'Yes',
				'0' => 'No',
			],
		],

		//Advanced
		'item_lang' => [
			'name' => 'item_lang',
			'id' => 'item_lang',
			'tip' => 'The language option allows you to specify which language Auction Nudge tools display on your site. This option will not modify eBay item titles, which will remain unchanged.',
			'tip_link' => 'https://www.auctionnudge.com/help/options#language',
			'type' => 'select',
			'options' => [
				'english' => 'English',
				'french' => 'French',
				'german' => 'German',
				'italian' => 'Italian',
				'spanish' => 'Spanish',
			],
			'default' => 'english',
			'group' => 'advanced',
			'title' => 'Language',
		],
		'item_sortOrder' => [
			'name' => 'item_sortOrder',
			'id' => 'item_sortOrder',
			'tip' => 'This option adjusts the order in which items are shown.',
			'type' => 'select',
			'options' => [
				'' => 'Items Ending First',
				'StartTimeNewest' => 'Newly-Listed First',
				'PricePlusShippingLowest' => 'Price + Shipping: Lowest First',
				'PricePlusShippingHighest' => 'Price + Shipping: Highest First',
				'BestMatch' => 'Best Match',
			],
			'group' => 'advanced',
			'title' => 'Sort Order',
		],
		'item_listing_type' => [
			'name' => 'item_listing_type',
			'id' => 'item_listing_type',
			'tip' => 'Filtering by listing type allows you to choose to only display items listed as either Auction or Buy It Now. Auction listings that have the Buy It Now option available will be displayed both when filtering by Auction and Buy It Now.',
			'group' => 'advanced',
			'title' => 'Listing Type',
			'type' => 'select',
			'options' => [
				'' => 'All Listings',
				'bin_only' => 'Buy It Now Only',
				'auction_only' => 'Auction Only',
			],
		],
		'item_keyword' => [
			'name' => 'item_keyword',
			'id' => 'item_keyword',
			'tip' => 'By specifying a keyword, only items which contain that keyword in their title will be displayed. The keyword query can contain search operators, allowing for powerful searches to include/exclude certain keywords. Note: it is not possible to just use the minus sign (NOT) operator alone, another operator must be used to include items.',
			'tip_link' => 'https://www.auctionnudge.com/help/options#keyword-filter',
			'group' => 'advanced',
			'title' => 'Filter by Keyword',
			'output_processing' => [
				'keyword_encode',
			],
		],
		'item_categoryId' => [
			'name' => 'item_categoryId',
			'id' => 'item_categoryId',
			'tip' => 'By specifying an eBay category ID, only items which are listed in this category will be displayed.',
			'tip_link' => 'https://www.auctionnudge.com/help/options#category-filter',
			'group' => 'advanced',
			'title' => 'Filter by Category ID',
		],
	],
];
